Repository MeliZeraveis/integration-project-fresh, pull requests merged in 2022-11, with the labels that each got.

#4 Req 2: Purchase order models
  src/main/java/br/dh/meli/integratorprojectfresh/enums/OrderStatus.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/Announcement.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/PurchaseOrder.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/PurchaseOrderItems.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/User.java
Labels: enhancement

#13 feature/requisito-4
  src/main/java/br/dh/meli/integratorprojectfresh/controller/AnnoucementController.java
  src/main/java/br/dh/meli/integratorprojectfresh/controller/InboundOrderController.java
  src/main/java/br/dh/meli/integratorprojectfresh/controller/WarehouseController.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/InboundOrderRequestDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/request/BatchStockDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/response/AnnoucementGetResponseDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/response/BatchStockQuantityResponseDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/response/WarehouseProductQuantityGetResponseDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/repository/AnnouncementRepository.java
  src/main/java/br/dh/meli/integratorprojectfresh/service/AnnouncementService.java
  src/main/java/br/dh/meli/integratorprojectfresh/service/IWareshouseService.java
  src/main/java/br/dh/meli/integratorprojectfresh/service/WarehouseService.java
  src/main/resources/application-test.properties
  src/test/java/br/dh/meli/integratorprojectfresh/integration/WareHouseControllerTestIT.java
  src/test/java/br/dh/meli/integratorprojectfresh/service/WarehouseServiceTest.java
Labels: enhancement

#22 fix: validation checks not working
  pom.xml
  src/main/java/br/dh/meli/integratorprojectfresh/annotations/OneOf.java
  src/main/java/br/dh/meli/integratorprojectfresh/annotations/OneOfValidator.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/request/BatchStockDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/request/PurchaseOrderItemsRequestDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/request/PurchaseOrderRequestDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/response/PurchaseOrderResponseDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/enums/Msg.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/PurchaseOrder.java
  src/main/java/br/dh/meli/integratorprojectfresh/service/PurchaseOrderService.java
  src/main/resources/application-dev.properties
  src/main/resources/application-test.properties
Labels: bug

#31 spring-dotenv config
  .gitignore
  pom.xml
  src/main/java/br/dh/meli/integratorprojectfresh/IntegratorProjectFreshApplication.java
  src/main/resources/.env.example
  src/main/resources/application-dev.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
Labels: enhancement

#36 Release/version 0.0.6
  .DS_Store
  .gitignore
  README.md
  docs/.DS_Store
  docs/1. Inbound Order.postman_collection.json
  docs/2. Purchase Orders.postman_collection.json
  docs/3. Products.postman_collection.json
  docs/4.Wharehouse.postman_collection.json
  docs/5. Batch Stock.postman_collection.json
  docs/diagrama-entidades.png
  pom.xml
  src/main/java/br/dh/meli/integratorprojectfresh/IntegratorProjectFreshApplication.java
  src/main/java/br/dh/meli/integratorprojectfresh/controller/BatchStockController.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/request/InboundOrderDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/request/InboundOrderRequestDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/request/SectionDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/response/AnnouncementGetResponseDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/dto/response/BatchStockGetResponseDTO.java
  src/main/java/br/dh/meli/integratorprojectfresh/enums/OrderStatus.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/Announcement.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/InboundOrder.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/Section.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/User.java
  src/main/java/br/dh/meli/integratorprojectfresh/model/Warehouse.java
  src/main/java/br/dh/meli/integratorprojectfresh/repository/SectionRepository.java
  src/main/java/br/dh/meli/integratorprojectfresh/service/IAnnouncementService.java
  src/main/java/br/dh/meli/integratorprojectfresh/service/IBatchStockService.java
  src/main/java/br/dh/meli/integratorprojectfresh/service/InboundOrderService.java
  src/main/resources/.env.example
  src/main/resources/Dump20221116.sql
  src/main/resources/application-dev.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/br/dh/meli/integratorprojectfresh/integration/AnnoucementControllerTestIT.java
  src/test/java/br/dh/meli/integratorprojectfresh/integration/InboundOrderControllerTestIT.java
  src/test/java/br/dh/meli/integratorprojectfresh/integration/PurchaseOrderControllerTestIT.java
  src/test/java/br/dh/meli/integratorprojectfresh/service/AnnouncementServiceTest.java
  src/test/java/br/dh/meli/integratorprojectfresh/service/BatchStockServiceTest.java
  src/test/java/br/dh/meli/integratorprojectfresh/service/InboundOrderServiceTest.java
  src/test/java/br/dh/meli/integratorprojectfresh/service/PurchaseOrderServiceTest.java
Labels: version
